# -*- coding: utf-8 -*-
"""Random-Forest-Regression.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/17ekCUVAgIbFWqzgO49dFbo8ZDDzdwRiO

##Importing Libraries
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

"""##Importing Dataset"""

dataset = pd.read_csv("Position_Salaries.csv")
X = dataset.iloc[:, 1:-1].values
y = dataset.iloc[:, -1].values
y = y.reshape(len(y), 1)

print(X)

print(y)

"""##Training The Random Forest Regression on The Whole Dataset"""

from sklearn.ensemble import RandomForestRegressor
RF_regressor = RandomForestRegressor(n_estimators=10, random_state=0)
RF_regressor.fit(X, y)

"""##Predict a New Point"""

y_pred = RF_regressor.predict([[6.5]])
print("The predicted salary for a level of 6.5 is ", y_pred[0])

"""##Visualizing The Decision Tree Regression Results for Higher Resolution"""

X_grid = np.arange(min(X), max(X), 0.1)
X_grid = np.reshape(X_grid, (len(X_grid), 1))
plt.scatter(X, y, color="red")
plt.plot(X_grid, RF_regressor.predict(X_grid))
plt.title("Truth or Bluff (Random Forest Regression)")
plt.xlabel("Position Level")
plt.ylabel("Salary")
plt.show()