# -*- coding: utf-8 -*-
"""Multiple-Linear-Regression.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1-lWZXF05Nf4x8AAJtYoglY0hgERQXjgq

## Importing Libraries
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

"""##Importing Dataset"""

dataset = pd.read_csv('50_Startups.csv')
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

print(X)

print(y)

"""##Encoding Categorical Data"""

from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [3])], remainder='passthrough')
X = np.array(ct.fit_transform(X))

print(X)

"""##Split Dataset"""

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state=0)

"""##Training the Multiple Linear Regression model

### Multiple Linear Regression Equation
$y = b_{0} + b_{1}x_{1} + b_{2}x_{2} + ... + b_{n}x_{n}$

"""

from sklearn.linear_model import LinearRegression
regressor = LinearRegression()
regressor.fit(X_train, y_train)

#Question 1: How do I use my multiple linear regression model to make a single prediction,
#for example, the profit of a startup with:
#R&D Spend = 160000,
#Administration Spend = 130000,
#Marketing Spend = 300000 and,
#State = California?

### Answer
b = regressor.coef_
b0 = regressor.intercept_

single_y_pred = b0 + b[0] * 1.0 + b[3] * 160000 + b[4] * 130000 + b[5] * 300000
single_y_pred

"""##Predicting The Test Set Results"""

y_pred = regressor.predict(X_test)
np.set_printoptions(precision=2)
print(np.concatenate((y_pred.reshape(len(y_pred), 1), y_test.reshape(len(y_pred), 1)), 1))