# -*- coding: utf-8 -*-
"""Apriori.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Y398aBy4ktmVXDlg1tHdPIqHsXNUphAo

##Importing Libraries
"""

!pip install apyori

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

"""##Data Preproccessing"""

dataset = pd.read_csv('Market_Basket_Optimisation.csv', header = None)
transactions = []
# dataset = dataset.to_numpy()
# print(dataset)

for i in range(0, 7501):
  transactions.append([str(dataset.values[i, k]) for k in range(0, 20)])

"""##Traning The Apriori Model on The Dataset"""

from apyori import apriori
rules = apriori(transactions= transactions, min_support=0.003, min_confidence= 0.2, min_lift=3, min_length=2, max_length=2)

"""##Visualizing The Results"""

results = list(rules)
results

"""##Putting The Results Well Organised into a Pandas DataFrame"""

def inspect(results):
  lhs = [tuple(result[2][0][0])[0] for result in results]
  rhs = [tuple(result[2][0][1])[0] for result in results]
  supports = [result[1] for result in results]
  confidences = [result[2][0][2] for result in results]
  lifts = [result[2][0][3] for result in results]
  return list(zip(lhs, rhs, supports, confidences, lifts))
resultsInDataFrame = pd.DataFrame(inspect(results), columns = ['Left Hand Side', 'Right Hand Side', 'Support', 'Confidence', 'Lift' ])

"""##Displaying The Results Non-Sorted



"""

resultsInDataFrame

"""####Displaying The Results Sorted by Descending Lifts

"""

resultsInDataFrame.nlargest(n=10, columns=['Lift'])