# -*- coding: utf-8 -*-
"""Linear-Regression.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ZrCiGY_uz3FKT3alKXJrF6AwJgvBsigL

##Import Libraries
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

"""##Import Data Set"""

dataset = pd.read_csv('Salary_Data.csv')
X = dataset.iloc[:, :-1].values
Y = dataset.iloc[:, -1].values

"""##Splitting data into training and test sets"""

from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size = 0.2, random_state = 0)

"""##Simple Linear Regression Training"""

from sklearn.linear_model import LinearRegression
regressor = LinearRegression()
regressor.fit(X_train, Y_train)

"""##Predicting the test set results"""

y_pred = regressor.predict(X_test)

"""##Visualizing Training Result

"""

plt.scatter(X_train, Y_train, color = 'red')
plt.plot(X_train, regressor.predict(X_train), color = 'blue')
plt.title('Salary VS Experience')
plt.show()

"""##Visualizing Test Set Results"""

plt.scatter(X_test, Y_test, color = 'red')
#we will have the same line even if we put training set in plot method
#plt.plot(X_test, y_pred, color = 'black')
plt.plot(X_train, regressor.predict(X_train), color = 'blue')
plt.title('Salary VS Experience')
plt.show()